[package]
name = "std"
version = "0.0.1"
authors = []


[dependencies.core]
path = "../core"

[dependencies.alloc]
path = "../alloc"

[dependencies.rand]
path = "../rand"

[dependencies.rustc_unicode]
path = "../unicode"

[dependencies.collections]
path = "../collections"
